### ISSUE TITLE
Moving into main repository

### ISSUE THREAD

**Issue by parsfounder** [e107inc/twofactorauth#4]
As long as this feature is essential and it appears on every platforms nowadays, so why is this separated from the main repository?

**Comment by Moc** [comment]
Short answer: because the functionalities that this plugin offers are not yet well enough developed and tested. 

Long answer: So far, I have had almost no feedback from anyone using the plugin. 

In addition, there are some open issues that I'd like to resolve before creating another release. These concern features that, in my opinion, are essential for this plugin. 

I do agree that, once the plugin has proven it's stability, it could be merged into core. I then see two options:

1.  Either through the release process where the plugin is included in the full release zip file (while this plugin maintains its own GitHub repository), 
2. Or merged into into the core repository as a new plugin folder. 

For now however, it's easier to develop the functionalities in a separate repository (e.g. managing issues / feedback, managing releases, having a roadmap specific to this plugin). In time, these advantages can also be applied to the core repository but not yet. 

Also, I'd like to strengthen its user friendliness and add some more documentation. 

So, if people would like to test and provide feedback, that would be much appreciated.
